import test from 'node:test';
import assert from 'node:assert/strict';
import {circleIntersections,planarIK,jansen,JANSEN_EDGES,fabrik,distance,crankSlider,parseCircuit,solveCircuit,astar,sceneCommand,rewrite,type V3} from '../src/math';
import crambin from '../src/data/crambin.json';

test('两圆交点分别满足两条杆长；无解装配不返回 NaN',()=>{for(let i=0;i<80;i++){const a={x:1,y:-2},b={x:4,y:Math.sin(i)*.4};const r=circleIntersections(a,3,b,2);assert.ok(r.ok);for(const p of r.points){assert.ok(Math.abs(Math.hypot(p.x-a.x,p.y-a.y)-3)<1e-10);assert.ok(Math.abs(Math.hypot(p.x-b.x,p.y-b.y)-2)<1e-10);}}assert.equal(circleIntersections({x:0,y:0},1,{x:5,y:0},1).ok,false);assert.equal(circleIntersections({x:0,y:0},1,{x:0,y:0},1).ok,false);});
test('Jansen 一整圈、两个分支均保持 12 条杆长',()=>{for(const mirror of[false,true])for(let i=0;i<360;i++){const r=jansen(i*Math.PI/180,mirror);assert.ok(r.ok,`角度 ${i}`);assert.equal(r.points.length,8);for(const[a,b,l]of JANSEN_EDGES)assert.ok(Math.abs(Math.hypot(r.points[a].x-r.points[b].x,r.points[a].y-r.points[b].y)-l)<1e-8);}});
test('IK 的两种肘分支都到达目标，拒绝过远和内侧盲区',()=>{for(const branch of[-1,1])for(let a=0;a<6;a+=.15){const r=planarIK(3*Math.cos(a),3*Math.sin(a),2,2,branch);assert.ok(r.ok);assert.ok(r.error<1e-10);assert.ok(Math.abs(Math.hypot(r.knee.x,r.knee.y)-2)<1e-10);}assert.equal(planarIK(10,0,2,2).ok,false);assert.equal(planarIK(.1,0,3,1).ok,false);});
test('FABRIK 固定根部、保持链长、区分可达与超长目标',()=>{const chain:V3[]=Array.from({length:21},(_,i)=>[i*.5,0,0]);for(const target of[[4,3,1],[13,0,0]]as V3[]){const r=fabrik(chain,target,.5,100);assert.deepEqual(r.points[0],chain[0]);for(let i=1;i<r.points.length;i++)assert.ok(Math.abs(distance(r.points[i],r.points[i-1])-.5)<1e-8);assert.equal(r.reachable,target[0]<10);if(r.reachable)assert.ok(r.error<.001);else assert.ok(Math.abs(r.error-3)<1e-8);}});
test('倾斜气缸的曲柄滑块连杆距离保持不变',()=>{for(const bank of[-1,1])for(let a=0;a<Math.PI*2;a+=.03){const norm=Math.hypot(1,bank*.5),dy=1/norm,dz=bank*.5/norm,r=.45,l=1.8,tr=crankSlider(a,r,l);const pin:V3=[0,r*(Math.cos(a)*dy-Math.sin(a)*dz),r*(Math.cos(a)*dz+Math.sin(a)*dy)],piston:V3=[0,tr*dy,tr*dz];assert.ok(Math.abs(distance(pin,piston)-l)<1e-10);}assert.throws(()=>crankSlider(0,2,1));});
const divider={nodes:['0','in','out'],parts:[{id:'V',type:'voltage-source',pins:['in','0'],value:12},{id:'R1',type:'resistor',pins:['in','out'],value:1000},{id:'R2',type:'resistor',pins:['out','0'],value:1000}]};
test('MNA 分压、极性反转和不等阻值的可核算结果',()=>{const c=parseCircuit(JSON.stringify(divider));assert.equal(solveCircuit(c).out,6);c.parts[0].value=-12;assert.equal(solveCircuit(c).out,-6);c.parts[0].value=9;c.parts[2].value=2000;assert.ok(Math.abs(solveCircuit(c).out-6)<1e-10);});
test('网表拒绝重复 ID、非法引脚、零电阻、孤立节点和矛盾电源',()=>{for(const modify of[(c:any)=>c.parts[1].id='V',(c:any)=>c.parts[1].pins=['missing','0'],(c:any)=>c.parts[1].value=0]){const c=structuredClone(divider);modify(c);assert.throws(()=>parseCircuit(JSON.stringify(c)));}const c=parseCircuit(JSON.stringify(divider));c.nodes.push('floating');assert.throws(()=>solveCircuit(c),/奇异/);const d=parseCircuit(JSON.stringify(divider));d.parts.push({...d.parts[0],id:'V2',value:3});assert.throws(()=>solveCircuit(d),/奇异/);});
test('A* 绕过货架，路径连续且不会越界；封闭目标返回无路径',()=>{const blocked=new Set(['2,0','2,1','2,2','2,3']);const path=astar(5,5,blocked,[0,0],[4,0]);assert.ok(path);assert.equal(path.length,13);for(let i=0;i<path.length;i++){assert.ok(!blocked.has(path[i].join(',')));if(i)assert.equal(Math.abs(path[i][0]-path[i-1][0])+Math.abs(path[i][1]-path[i-1][1]),1);}blocked.add('2,4');assert.equal(astar(5,5,blocked,[0,0],[4,0]),null);assert.equal(astar(5,5,blocked,[-1,0],[4,0]),null);});
test('场景命令校验失败时原场景完整，清空与删除可预测',()=>{const raw={op:'add',objects:[{id:'a',type:'box',position:[0,1,0],size:1,color:'#123456'}]};const current=sceneCommand(JSON.stringify(raw),[]);assert.equal(current.length,1);for(const modify of[(r:any)=>r.objects[0].type='script',(r:any)=>r.objects[0].size=100,(r:any)=>r.objects[0].position=[0,99,0]]){const r=structuredClone(raw);r.objects[0].id='b';modify(r);assert.throws(()=>sceneCommand(JSON.stringify(r),current));assert.equal(current.length,1);}assert.throws(()=>sceneCommand(JSON.stringify(raw),current));assert.equal(sceneCommand('{"op":"remove","ids":["a"]}',current).length,0);assert.equal(sceneCommand('{"op":"clear"}',current).length,0);});
test('图重写保留 ID、确定性与预算边界',()=>{const initial={nextId:2,edges:[[0,1]]as[number,number][],steps:0,trace:[]as string[]};let graph=initial;for(let i=0;i<10;i++)graph=rewrite(graph,12);assert.equal(graph.nextId,12);assert.equal(graph.edges.length,21);assert.throws(()=>rewrite(graph,12));assert.deepEqual(rewrite(initial,12),rewrite(initial,12));assert.equal(initial.nextId,2);assert.ok(graph.edges.every(([a,b])=>a>=0&&b>=0&&a<graph.nextId&&b<graph.nextId));});
test('1CRN 真实坐标档案包含 46 个唯一 Cα 残基与来源哈希',()=>{assert.equal(crambin.atoms.length,46);assert.equal(new Set(crambin.atoms.map(a=>a.id)).size,46);assert.ok(crambin.atoms.every(a=>a.xyz.length===3&&a.xyz.every(Number.isFinite)));assert.match(crambin.sourceSha256,/^[a-f0-9]{64}$/);});
